repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: isort
        stages: [commit]
        name: isort
        entry: pipenv run isort --profile black
        language: system
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.6.4
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--filter-files"]
