version: "3.8"

services:
  app:
    networks:
      - yurucamp
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    env_file: .env.compose
    ports:
      - "8000:8000"
    volumes:
      - "./yurucamp:/code/"
    depends_on:
      database:
        condition: service_healthy

  database:
    networks:
      - yurucamp
    container_name: db
    image: bitnami/postgresql:14
    ports:
      - "5432:5432"
    volumes:
      - postgres-yurucamp:/data/db
    environment:
      - POSTGRESQL_USERNAME=yc
      - POSTGRESQL_PASSWORD=pass1234
      - POSTGRESQL_DATABASE=yurucamp
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=yurucamp", "--username=yc"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  postgres-yurucamp:

networks:
  yurucamp:
