# Generated by Django 4.2.7 on 2023-11-05 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(db_index=True, max_length=3)),
                ("city_code", models.CharField(max_length=255)),
                ("city_display_name", models.CharField(max_length=255)),
                (
                    "city_coords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(
                            decimal_places=10, max_digits=20
                        ),
                        max_length=2,
                        size=None,
                    ),
                ),
            ],
            options={
                "db_table": "locations",
            },
        ),
    ]
