# Generated by Django 4.2.7 on 2023-11-05 08:08
import json
import pathlib

from django.db import migrations


def populate_locations(apps, schema_editor):
    Location = apps.get_model("planner", "Location")

    path = f"{pathlib.Path(__file__).parents[2]}/data/locations.json"
    with open(path, "r") as f:
        data = json.load(f)

        for rec in data["locations"]:
            Location(**rec).save()


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_locations),
    ]
