# Generated by Django 4.2.7 on 2023-11-07 03:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0002_auto_20231105_0808"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gid", models.UUIDField(default=uuid.uuid1, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.BigIntegerField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (10, "Draft"),
                            (20, "Published"),
                            (30, "Ongoing"),
                            (100, "Completed"),
                        ]
                    ),
                ),
                ("locations", models.JSONField()),
            ],
            options={
                "db_table": "trips",
            },
        ),
    ]
