# Generated by Django 4.2.7 on 2023-11-13 11:05

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):
    dependencies = [
        ("planner", "0004_alter_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="gid",
            field=models.CharField(
                default=helpers.generate_id, max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="gid",
            field=models.CharField(
                default=helpers.generate_id, max_length=50, unique=True
            ),
        ),
    ]
